// server/modules/consolidation/consolidation.constants.ts

export const CONSOLIDATION_DEFAULTS = {
  CACHE_TTL_SECONDS: 300, // 5 minutes cache
  DASHBOARD_CACHE_KEY: "consolidation:cache:dashboard_summary",
  BALANCE_SHEET_CACHE_KEY: "consolidation:cache:balance_sheet",
  INCOME_STATEMENT_CACHE_KEY: "consolidation:cache:income_statement",
  CASH_FLOW_CACHE_KEY: "consolidation:cache:cash_flow",
  TRIAL_BALANCE_CACHE_KEY: "consolidation:cache:trial_balance",
  INVENTORY_CACHE_KEY: "consolidation:cache:inventory",
  
  MAIN_BRANCH_CODE: "BRH-MAIN-001",
  SYSTEM_USER: "SYSTEM_CONSOLIDATION_ENGINE",
  
  // Account Category mapping codes for standard charts of accounts
  ACCOUNTS_CASH_PREFIX: "1000",
  ACCOUNTS_RECEIVABLE_PREFIX: "1100",
  ACCOUNTS_INVENTORY_PREFIX: "1200",
  ACCOUNTS_OTHER_CURRENT_ASSETS_PREFIX: "1300",
  ACCOUNTS_NON_CURRENT_ASSETS_PREFIX: "1500",
  ACCOUNTS_PAYABLE_PREFIX: "2000",
  ACCOUNTS_OTHER_CURRENT_LIABILITIES_PREFIX: "2100",
  ACCOUNTS_NON_CURRENT_LIABILITIES_PREFIX: "2300",
  ACCOUNTS_EQUITY_PREFIX: "3000",
  ACCOUNTS_REVENUE_PREFIX: "4000",
  ACCOUNTS_COGS_PREFIX: "5000",
  ACCOUNTS_OPEX_SALARY_PREFIX: "6000",
  ACCOUNTS_OPEX_RENT_PREFIX: "6100",
  ACCOUNTS_OPEX_UTILITIES_PREFIX: "6200",
  ACCOUNTS_OPEX_MARKETING_PREFIX: "6300",
  ACCOUNTS_OPEX_OTHER_PREFIX: "6500",
  ACCOUNTS_TAX_PREFIX: "7000",
};

export const ELIMINATION_RULES = {
  ELIMINATE_COMPLETED_TRANSFERS: true,
  ELIMINATE_INTERNAL_TRADING: true,
  ELIMINATE_INTERNAL_MOVEMENTS: true,
};
