// server/modules/replication/replication.service.ts

import { prisma } from "../../database/prisma";
import { ReplicationEvent, BusinessEventType, SyncRecoveryRequest, SyncRecoveryResponse } from "./replication.types";
import { RedisConnectionManager } from "../../database/redis";

export class ReplicationService {
  /**
   * Recovers missed replication events for a branch that was offline or disconnected.
   * Matches sequence number and target branch isolation logic.
   */
  static async recoverMissedEvents(request: SyncRecoveryRequest, userId?: string): Promise<SyncRecoveryResponse> {
    const { branchId, lastKnownSequence } = request;

    console.log(`[REPLICATION_SERVICE] Initiate recovery for branch ${branchId}. Last known local sequence: ${lastKnownSequence}`);

    try {
      // Find all SyncEvents in DB with sequence ID greater than lastKnownSequence
      // Since sequence is a BigInt, we can filter elements where sequence > BigInt(lastKnownSequence)
      const rawEvents = await prisma.syncEvent.findMany({
        where: {
          sequence: {
            gt: BigInt(lastKnownSequence)
          }
        },
        orderBy: {
          sequence: "asc"
        },
        take: 500 // Limit chunk size to prevent browser/network overflow
      });

      // Filter events to find those relevant to this branch:
      // - Events that weren't published by this branch (to prevent feedback lock)
      // - Events destined for this branch, or globally broadcasted ("group:all")
      const recoveredEvents: ReplicationEvent[] = rawEvents
        .map((evt) => {
          return {
            id: evt.eventId,
            type: evt.eventType as BusinessEventType,
            branchId: evt.branchId || "unknown",
            timestamp: evt.clientTime.toISOString(),
            payload: evt.payload,
            sequence: Number(evt.sequence),
            vectorClock: (evt.vectorClock as Record<string, number>) || {},
            checksum: evt.checksum || undefined,
          };
        })
        .filter((evt) => {
          // If the event was generated by another branch, then we can synchronize it to this branch
          return evt.branchId !== branchId;
        });

      // Log immutable audit event for recovery
      if (recoveredEvents.length > 0) {
        await prisma.auditLog.create({
          data: {
            action: "REPLICATION_RECOVERED",
            entity: "Branch",
            entityId: branchId,
            before: JSON.stringify({ lastKnownSequence }),
            after: JSON.stringify({
              recoveredCount: recoveredEvents.length,
              recoveredSequences: recoveredEvents.map(e => e.sequence)
            }),
            userId: userId || "system",
            branchId,
          }
        });

        console.log(`[REPLICATION_SERVICE] Replayed ${recoveredEvents.length} missed events to branch ${branchId}`);
      }

      return {
        recoveredEvents,
        isFullySynced: rawEvents.length < 500 // if we got less than the max capacity chunk, we assume fully synced
      };
    } catch (err: any) {
      console.error(`[REPLICATION_SERVICE] Missed event recovery failed for branch ${branchId}:`, err.message);
      return {
        recoveredEvents: [],
        isFullySynced: false
      };
    }
  }

  /**
   * Manual replay of a historical queue by admin/accountants.
   */
  static async replayEventStream(params: {
    originBranchId?: string;
    type?: BusinessEventType;
    limit?: number;
    userId?: string;
  }): Promise<ReplicationEvent[]> {
    const { limit = 100, originBranchId, type } = params;

    try {
      const parentWhere: any = {};
      if (originBranchId) {
        parentWhere.branchId = originBranchId;
      }
      if (type) {
        parentWhere.eventType = type;
      }

      const rawEvents = await prisma.syncEvent.findMany({
        where: parentWhere,
        orderBy: {
          sequence: "desc"
        },
        take: limit
      });

      const processedEvents = rawEvents.map((evt) => ({
        id: evt.eventId,
        type: evt.eventType as BusinessEventType,
        branchId: evt.branchId || "unknown",
        timestamp: evt.clientTime.toISOString(),
        payload: evt.payload,
        sequence: Number(evt.sequence),
        vectorClock: (evt.vectorClock as Record<string, number>) || {},
        checksum: evt.checksum || undefined,
      })).reverse();

      // Log auditing record for system replay
      await prisma.auditLog.create({
        data: {
          action: "REPLICATION_REPLAYED",
          entity: "System",
          entityId: "ReplayStream",
          before: JSON.stringify(params),
          after: JSON.stringify({ replayedCount: processedEvents.length }),
          userId: params.userId || "system",
        }
      });

      return processedEvents;
    } catch (err: any) {
      console.error("[REPLICATION_SERVICE] Failed to replay event stream queue:", err.message);
      return [];
    }
  }

  /**
   * Check total event logs and sync status metrics.
   */
  static async getReplicationMetrics(): Promise<{
    redisConnected: boolean;
    syncEventsCount: number;
    auditLogsEventsCount: number;
  }> {
    const redis = RedisConnectionManager.getClient();
    const redisConnected = redis !== null && !(RedisConnectionManager as any).isMemoryFallback;
    
    let syncEventsCount = 0;
    let auditLogsEventsCount = 0;
    
    try {
      syncEventsCount = await prisma.syncEvent.count();
      auditLogsEventsCount = await prisma.auditLog.count({
        where: {
          action: {
            in: ["REPLICATION_PUBLISHED", "REPLICATION_RECEIVED", "REPLICATION_REPLAYED", "REPLICATION_RECOVERED"]
          }
        }
      });
    } catch (err) {
      // Ignored / count fallback
    }

    return {
      redisConnected,
      syncEventsCount,
      auditLogsEventsCount
    };
  }
}
