name: Cleanup Project
on:
  workflow_dispatch:

jobs:
  remove-web-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete Unwanted Files
        run: |
          rm -rf server.ts package.json package-lock.json tsconfig.json vite.config.ts src/ public/
          echo "تم تنظيف ملفات الويب بنجاح"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "تنظيف المستودع من ملفات الويب" || exit 0
          git push
          
